(function initTeleseerAlertingData(global) {
  const projectPool = [
    "teleseer-dummy",
    "Site Julio",
    "Hospital East Wing",
    "Coastal Relay Mirror",
    "Power Plant",
    "Widget Factory",
    "Military Base",
    "Lab Aggregate",
  ];

  const variableDefs = [
    {
      name: "HOME_NET",
      type: "Subnet",
      literalValues: [
        "10.10.4.0/24",
        "10.10.8.0/24",
        "172.18.31.0/24",
        "192.168.44.0/24",
      ],
      referenceItems: [],
      createdAt: "2025-10-18T07:53:30Z",
      updatedAt: "2026-04-18T21:16:54Z",
    },
    {
      name: "REMOTE_USERS_NET",
      type: "Subnet",
      literalValues: ["198.51.100.0/24", "203.0.113.0/25"],
      referenceItems: ["HOME_NET"],
      createdAt: "2026-01-29T11:03:26Z",
      updatedAt: "2026-04-15T08:36:08Z",
    },
    {
      name: "DMZ_NET",
      type: "Subnet",
      literalValues: ["10.66.19.0/24", "172.16.88.0/24", "192.0.2.64/27"],
      referenceItems: [],
      createdAt: "2025-12-02T15:09:51Z",
      updatedAt: "2026-04-17T16:08:12Z",
    },
    {
      name: "EXTERNAL_NET",
      type: "Subnet",
      literalValues: ["203.0.113.0/24", "198.51.100.0/24", "185.199.108.0/24"],
      referenceItems: [],
      createdAt: "2025-11-20T09:14:42Z",
      updatedAt: "2026-04-19T09:51:10Z",
    },
    {
      name: "THREAT_FEED_NET",
      type: "Subnet",
      literalValues: [
        "185.199.108.0/22",
        "91.218.230.0/24",
        "203.0.113.128/25",
        "198.51.100.128/25",
        "192.0.2.160/27",
      ],
      referenceItems: ["EXTERNAL_NET"],
      createdAt: "2026-03-07T06:22:40Z",
      updatedAt: "2026-04-21T19:58:11Z",
    },
    {
      name: "VPN_USERS_NET",
      type: "Subnet",
      literalValues: ["198.51.100.64/26", "203.0.113.192/26"],
      referenceItems: ["HOME_NET", "REMOTE_USERS_NET"],
      createdAt: "2026-02-16T13:05:11Z",
      updatedAt: "2026-04-20T07:21:44Z",
    },
    {
      name: "HTTP_PORTS",
      type: "Port",
      literalValues: ["80", "81", "8080", "8888"],
      referenceItems: [],
      createdAt: "2026-01-14T08:12:19Z",
      updatedAt: "2026-04-19T13:32:44Z",
    },
    {
      name: "HTTPS_PORTS",
      type: "Port",
      literalValues: [
        "443",
        "8443",
        "9443",
        "10443",
        "11443",
        "12443",
        "13443",
        "14443",
        "15443",
        "16443",
        "17443",
        "18443",
      ],
      referenceItems: ["HTTP_PORTS"],
      createdAt: "2025-11-22T12:05:44Z",
      updatedAt: "2026-04-20T17:41:07Z",
    },
    {
      name: "SSH_PORTS",
      type: "Port",
      literalValues: ["22", "2222", "22022-22454"],
      referenceItems: [],
      createdAt: "2025-09-03T19:44:11Z",
      updatedAt: "2026-04-12T10:02:33Z",
    },
    {
      name: "VPN_PORTS",
      type: "Port",
      literalValues: ["1194", "51820"],
      referenceItems: ["SSH_PORTS"],
      createdAt: "2026-02-05T14:27:09Z",
      updatedAt: "2026-04-16T09:18:21Z",
    },
    {
      name: "PROXY_PORTS",
      type: "Port",
      literalValues: ["3128", "8080"],
      referenceItems: ["HTTP_PORTS", "HTTPS_PORTS"],
      createdAt: "2026-02-11T18:39:08Z",
      updatedAt: "2026-04-18T08:43:27Z",
    },
    {
      name: "OT_CONTROL_PORTS",
      type: "Port",
      literalValues: ["502", "20000", "44818", "47808"],
      referenceItems: [],
      createdAt: "2026-03-18T10:20:19Z",
      updatedAt: "2026-04-22T11:10:37Z",
    },
  ];

  function makeSubnetSelection({
    subnets = [],
    destinationSubnets = [],
    sourceSubnets = [],
  } = {}) {
    return {
      subnets: { mode: "include", checked: subnets, manual: [] },
      destinationSubnets: { mode: "include", checked: destinationSubnets, manual: [] },
      sourceSubnets: { mode: "include", checked: sourceSubnets, manual: [] },
    };
  }

  const etpCatalogCounts = {
    "suricata-etp-root": 1240,
    "suricata-etp-active-threats": 260,
    "suricata-etp-active-threats-malware": 55,
    "suricata-etp-active-threats-exploit": 40,
    "suricata-etp-active-threats-exploit-kit": 18,
    "suricata-etp-active-threats-phishing": 32,
    "suricata-etp-active-threats-botcc": 45,
    "suricata-etp-active-threats-botcc-portgrouped": 14,
    "suricata-etp-active-threats-worm": 20,
    "suricata-etp-active-threats-shellcode": 18,
    "suricata-etp-active-threats-mobile-malware": 10,
    "suricata-etp-active-threats-coinmining": 6,
    "suricata-etp-active-threats-compromised": 2,
    "suricata-etp-c2-reputation": 170,
    "suricata-etp-c2-ciarmy": 42,
    "suricata-etp-c2-drop-spamhaus": 50,
    "suricata-etp-c2-dshield": 28,
    "suricata-etp-c2-tor": 34,
    "suricata-etp-c2-threatview-cs-c2": 16,
    "suricata-etp-scanning-dos": 80,
    "suricata-etp-scanning-dos-scan": 34,
    "suricata-etp-scanning-dos-dos": 26,
    "suricata-etp-scanning-dos-attack-response": 20,
    "suricata-etp-web": 160,
    "suricata-etp-web-client": 72,
    "suricata-etp-web-server": 58,
    "suricata-etp-web-specific-apps": 30,
    "suricata-etp-network-services": 250,
    "suricata-etp-network-services-dns": 64,
    "suricata-etp-network-services-smtp": 18,
    "suricata-etp-network-services-ftp": 18,
    "suricata-etp-network-services-netbios": 40,
    "suricata-etp-network-services-rpc": 20,
    "suricata-etp-network-services-voip": 10,
    "suricata-etp-network-services-sql": 26,
    "suricata-etp-network-services-snmp": 18,
    "suricata-etp-network-services-imap": 12,
    "suricata-etp-network-services-pop3": 10,
    "suricata-etp-network-services-icmp": 8,
    "suricata-etp-network-services-telnet": 10,
    "suricata-etp-network-services-tftp": 16,
    "suricata-etp-policy-visibility": 210,
    "suricata-etp-policy-visibility-infor": 18,
    "suricata-etp-policy-visibility-hunting": 16,
    "suricata-etp-policy-visibility-p2p": 14,
    "suricata-etp-policy-visibility-chat": 10,
    "suricata-etp-policy-visibility-games": 8,
    "suricata-etp-policy-visibility-user-agents": 24,
    "suricata-etp-policy-visibility-file-sharing": 20,
    "suricata-etp-policy-visibility-remote-access": 48,
    "suricata-etp-policy-visibility-dyn-dns": 22,
    "suricata-etp-policy-visibility-abused-service": 16,
    "suricata-etp-policy-visibility-inappropriate": 14,
    "suricata-etp-policy-visibility-policy": 20,
    "suricata-etp-industrial-scada": 70,
    "suricata-etp-industrial-scada-scada": 52,
    "suricata-etp-industrial-scada-special": 18,
    "suricata-etp-operational": 40,
    "suricata-etp-operational-current-events": 12,
    "suricata-etp-operational-ja3": 14,
    "suricata-etp-operational-misc": 4,
    "suricata-etp-operational-activex": 4,
    "suricata-etp-operational-adware-pup": 6,
    "suricata-etp-inactive": 0,
  };

  const etpExpansionRuleDefs = [
    {
      id: 30005,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Malware Beacon Loader over TLS",
      description: "Detects beaconing malware loader traffic using uncommon TLS server fingerprints.",
      severity: "critical",
      classType: "Trojan Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100510,
      relatedSid: 2100510,
      totalHits: 112,
      speedValue: 15,
      lastSeenValue: 34,
      versionId: "v3",
      schedule: "1h",
      timeRange: "24h",
      severityOverride: "critical",
      threshold: 4,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.4.0/24", "10.10.8.0/24"],
        destinationSubnets: ["203.0.113.0/24"],
        sourceSubnets: ["10.10.4.0/24"],
      }),
      variableUsage: ["HOME_NET", "EXTERNAL_NET", "HTTPS_PORTS", "THREAT_FEED_NET"],
      projects: ["Site Julio", "Coastal Relay Mirror"],
      references: [
        ["MITRE T1071.001 - Web Protocols", "https://attack.mitre.org/techniques/T1071/001/"],
        ["ET Malware Watchlist", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-malware",
      originFolderNodeId: "suricata-etp-active-threats-malware",
      folderLabel: "Malware",
      createdAt: "2025-12-11T07:12:19Z",
      updatedAt: "2026-04-20T13:51:02Z",
    },
    {
      id: 30006,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Public-Facing Exploit Probe",
      description: "Flags exploit probing against public-facing application endpoints and odd 404 bursts.",
      severity: "high",
      classType: "Web Application Attack",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100511,
      relatedSid: 2100511,
      totalHits: 84,
      speedValue: 22,
      lastSeenValue: 77,
      versionId: "v3",
      schedule: "6h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 6,
      quota: "per-host",
      protocols: "http",
      ports: "80,8080",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "HTTP_PORTS", "PROXY_PORTS"],
      projects: ["Widget Factory", "Hospital East Wing"],
      references: [
        ["MITRE T1190 - Exploit Public-Facing Application", "https://attack.mitre.org/techniques/T1190/"],
        ["ET Exploit Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-exploit",
      originFolderNodeId: "suricata-etp-active-threats-exploit",
      folderLabel: "Exploit",
      createdAt: "2025-11-26T12:45:11Z",
      updatedAt: "2026-04-21T06:37:18Z",
    },
    {
      id: 30007,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Credential Phishing Redirect Chain",
      description: "Tracks phishing redirects that funnel victims into credential harvest pages.",
      severity: "high",
      classType: "Phishing",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100512,
      relatedSid: 2100512,
      totalHits: 58,
      speedValue: 19,
      lastSeenValue: 118,
      versionId: "v3",
      schedule: "6h",
      timeRange: "7d",
      severityOverride: "high",
      threshold: 3,
      quota: "per-subnet",
      protocols: "http",
      ports: "80,443",
      subnetFilters: makeSubnetSelection({
        subnets: ["198.51.100.0/24"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["REMOTE_USERS_NET", "EXTERNAL_NET", "HTTP_PORTS", "HTTPS_PORTS"],
      projects: ["Site Julio", "Lab Aggregate"],
      references: [
        ["MITRE T1566 - Phishing", "https://attack.mitre.org/techniques/T1566/"],
        ["ET Phishing Reference", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-phishing",
      originFolderNodeId: "suricata-etp-active-threats-phishing",
      folderLabel: "Phishing",
      createdAt: "2025-10-29T10:14:30Z",
      updatedAt: "2026-04-17T15:04:12Z",
    },
    {
      id: 30008,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Botnet Controller Burst",
      description: "High-volume botcc controller bursts against common edge services.",
      severity: "critical",
      classType: "Trojan Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100513,
      relatedSid: 2100513,
      totalHits: 146,
      speedValue: 13,
      lastSeenValue: 21,
      versionId: "v3",
      schedule: "1h",
      timeRange: "24h",
      severityOverride: "critical",
      threshold: 7,
      quota: "global",
      protocols: "tcp",
      ports: "80,443,8080",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["198.51.100.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["EXTERNAL_NET", "HTTP_PORTS", "HTTPS_PORTS", "PROXY_PORTS"],
      projects: ["Coastal Relay Mirror", "Military Base"],
      references: [
        ["MITRE T1584 - Compromise Infrastructure", "https://attack.mitre.org/techniques/T1584/"],
        ["ET Botcc Reference", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-botcc",
      originFolderNodeId: "suricata-etp-active-threats-botcc",
      folderLabel: "Botcc",
      createdAt: "2025-12-17T09:18:44Z",
      updatedAt: "2026-04-22T13:25:10Z",
    },
    {
      id: 30009,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Worm Propagation Sweep",
      description: "Detects worm-style spread behavior across SMB and RPC adjacency.",
      severity: "high",
      classType: "Worm",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100514,
      relatedSid: 2100514,
      totalHits: 63,
      speedValue: 17,
      lastSeenValue: 139,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 5,
      quota: "global",
      protocols: "tcp",
      ports: "139,445,135",
      subnetFilters: makeSubnetSelection({
        subnets: ["172.18.31.0/24"],
        destinationSubnets: ["172.18.31.0/24"],
        sourceSubnets: ["172.18.31.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "SSH_PORTS"],
      projects: ["Hospital East Wing", "Military Base"],
      references: [
        ["MITRE T1047 - Windows Management Instrumentation", "https://attack.mitre.org/techniques/T1047/"],
        ["ET Worm Reference", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-worm",
      originFolderNodeId: "suricata-etp-active-threats-worm",
      folderLabel: "Worm",
      createdAt: "2025-11-14T08:41:18Z",
      updatedAt: "2026-04-20T16:42:55Z",
    },
    {
      id: 30010,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Coinminer Stratum Negotiation",
      description: "Flags coinmining stratum negotiations and long-lived TLS sessions.",
      severity: "medium",
      classType: "Coinmining",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100515,
      relatedSid: 2100515,
      totalHits: 37,
      speedValue: 10,
      lastSeenValue: 92,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 2,
      quota: "per-sensor",
      protocols: "tls",
      ports: "443,3333",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["185.199.108.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["EXTERNAL_NET", "HTTPS_PORTS", "THREAT_FEED_NET"],
      projects: ["Lab Aggregate", "Widget Factory"],
      references: [
        ["MITRE T1496 - Resource Hijacking", "https://attack.mitre.org/techniques/T1496/"],
        ["ET Coinmining Reference", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-coinmining",
      originFolderNodeId: "suricata-etp-active-threats-coinmining",
      folderLabel: "Coinmining",
      createdAt: "2026-01-04T11:25:19Z",
      updatedAt: "2026-04-23T09:42:21Z",
    },
    {
      id: 30011,
      source: "Emerging Threats PRO",
      category: "Active Threats",
      groupId: "suricata-emerging",
      name: "Compromised Host Callback",
      description: "Callback traffic from a suspected compromised host to a known bad network.",
      severity: "low",
      classType: "Compromised",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100516,
      relatedSid: 2100516,
      totalHits: 19,
      speedValue: 9,
      lastSeenValue: 166,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 1,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.8.0/24"],
        destinationSubnets: ["203.0.113.0/24"],
        sourceSubnets: ["192.0.2.160/27"],
      }),
      variableUsage: ["HOME_NET", "THREAT_FEED_NET", "HTTPS_PORTS"],
      projects: ["Site Julio"],
      references: [
        ["MITRE T1001 - Data Obfuscation", "https://attack.mitre.org/techniques/T1001/"],
        ["ET Compromise Reference", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-active-threats-compromised",
      originFolderNodeId: "suricata-etp-active-threats-compromised",
      folderLabel: "Compromised",
      createdAt: "2026-02-02T10:17:55Z",
      updatedAt: "2026-04-24T12:02:09Z",
    },
    {
      id: 30012,
      source: "Emerging Threats PRO",
      category: "C2 & Reputation",
      groupId: "suricata-emerging",
      name: "CIArmy Beaconing",
      description: "Matches outbound control traffic to CIArmy-tagged command nodes.",
      severity: "high",
      classType: "Potentially Bad Traffic",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100517,
      relatedSid: 2100517,
      totalHits: 67,
      speedValue: 12,
      lastSeenValue: 64,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 2,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["185.199.108.0/22"],
        sourceSubnets: ["10.10.4.0/24"],
      }),
      variableUsage: ["HOME_NET", "EXTERNAL_NET", "THREAT_FEED_NET", "HTTPS_PORTS"],
      projects: ["Coastal Relay Mirror", "Site Julio"],
      references: [
        ["CIArmy Feed Notes", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1071.001 - Web Protocols", "https://attack.mitre.org/techniques/T1071/001/"],
      ],
      folderNodeId: "suricata-etp-c2-ciarmy",
      originFolderNodeId: "suricata-etp-c2-ciarmy",
      folderLabel: "CIArmy",
      createdAt: "2025-12-08T08:37:11Z",
      updatedAt: "2026-04-18T15:08:54Z",
    },
    {
      id: 30013,
      source: "Emerging Threats PRO",
      category: "C2 & Reputation",
      groupId: "suricata-emerging",
      name: "Drop Reputation Match",
      description: "Outbound connection against a drop-listed reputation feed target.",
      severity: "high",
      classType: "Potentially Bad Traffic",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100518,
      relatedSid: 2100518,
      totalHits: 103,
      speedValue: 16,
      lastSeenValue: 58,
      versionId: "v2",
      schedule: "6h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 2,
      quota: "per-host",
      protocols: "tcp",
      ports: "80,443,8080",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.8.0/24"],
        destinationSubnets: ["203.0.113.128/25"],
        sourceSubnets: ["10.10.4.0/24"],
      }),
      variableUsage: ["HOME_NET", "EXTERNAL_NET", "HTTP_PORTS", "HTTPS_PORTS"],
      projects: ["Site Julio", "Hospital East Wing"],
      references: [
        ["Spamhaus DROP List", "https://www.spamhaus.org/drop/"],
        ["ET Reputation Notes", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-c2-drop-spamhaus",
      originFolderNodeId: "suricata-etp-c2-drop-spamhaus",
      folderLabel: "Drop (Spamhaus)",
      createdAt: "2025-11-18T09:47:25Z",
      updatedAt: "2026-04-19T10:35:04Z",
    },
    {
      id: 30014,
      source: "Emerging Threats PRO",
      category: "C2 & Reputation",
      groupId: "suricata-emerging",
      name: "Dshield Scan Match",
      description: "Matches activity against Dshield scan reputation indicators.",
      severity: "medium",
      classType: "Attempted Recon",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100519,
      relatedSid: 2100519,
      totalHits: 49,
      speedValue: 14,
      lastSeenValue: 83,
      versionId: "v2",
      schedule: "12h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 3,
      quota: "per-subnet",
      protocols: "tcp",
      ports: "22,3389,445",
      subnetFilters: makeSubnetSelection({
        subnets: ["172.18.31.0/24"],
        destinationSubnets: ["172.18.31.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "REMOTE_USERS_NET", "SSH_PORTS"],
      projects: ["Military Base", "Power Plant"],
      references: [
        ["Dshield IP Reputation", "https://www.dshield.org/"],
        ["ET Recon Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-c2-dshield",
      originFolderNodeId: "suricata-etp-c2-dshield",
      folderLabel: "Dshield",
      createdAt: "2026-01-18T13:29:02Z",
      updatedAt: "2026-04-21T08:47:29Z",
    },
    {
      id: 30015,
      source: "Emerging Threats PRO",
      category: "C2 & Reputation",
      groupId: "suricata-emerging",
      name: "TOR Exit Node to DMZ",
      description: "TOR-originated session reaching DMZ services over TLS.",
      severity: "medium",
      classType: "Potentially Bad Traffic",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100520,
      relatedSid: 2100520,
      totalHits: 76,
      speedValue: 11,
      lastSeenValue: 31,
      versionId: "v2",
      schedule: "6h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 2,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["198.51.100.0/24"],
        sourceSubnets: ["203.0.113.192/26"],
      }),
      variableUsage: ["DMZ_NET", "EXTERNAL_NET", "HTTPS_PORTS"],
      projects: ["Coastal Relay Mirror", "Lab Aggregate"],
      references: [
        ["TOR Project", "https://www.torproject.org/"],
        ["ET TOR Reference", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-c2-tor",
      originFolderNodeId: "suricata-etp-c2-tor",
      folderLabel: "TOR",
      createdAt: "2026-02-04T15:07:12Z",
      updatedAt: "2026-04-24T11:18:38Z",
    },
    {
      id: 30016,
      source: "Emerging Threats PRO",
      category: "C2 & Reputation",
      groupId: "suricata-emerging",
      name: "Threatview C2 Connection",
      description: "Command-and-control reachability that matches the Threatview reputation feed.",
      severity: "high",
      classType: "Potentially Bad Traffic",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100521,
      relatedSid: 2100521,
      totalHits: 28,
      speedValue: 9,
      lastSeenValue: 144,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "high",
      threshold: 2,
      quota: "per-sensor",
      protocols: "tcp",
      ports: "443,9443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["198.51.100.128/25"],
        sourceSubnets: ["10.10.8.0/24"],
      }),
      variableUsage: ["HOME_NET", "THREAT_FEED_NET", "HTTPS_PORTS", "VPN_USERS_NET"],
      projects: ["Widget Factory"],
      references: [
        ["Threatview C2 Notes", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1071 - Application Layer Protocol", "https://attack.mitre.org/techniques/T1071/"],
      ],
      folderNodeId: "suricata-etp-c2-threatview-cs-c2",
      originFolderNodeId: "suricata-etp-c2-threatview-cs-c2",
      folderLabel: "Threatview_CS_c2",
      createdAt: "2026-03-08T10:03:50Z",
      updatedAt: "2026-04-25T14:42:14Z",
    },
    {
      id: 30017,
      source: "Emerging Threats PRO",
      category: "Web",
      groupId: "suricata-emerging",
      name: "Webshell Multipart Upload",
      description: "Web client multipart uploads carrying a webshell-style payload.",
      severity: "high",
      classType: "Web Application Attack",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100522,
      relatedSid: 2100522,
      totalHits: 91,
      speedValue: 18,
      lastSeenValue: 41,
      versionId: "v3",
      schedule: "1h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 5,
      quota: "per-host",
      protocols: "http",
      ports: "80,8080,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.4.0/24"],
        destinationSubnets: ["10.66.19.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "HTTP_PORTS", "PROXY_PORTS"],
      projects: ["Site Julio", "Widget Factory"],
      references: [
        ["MITRE T1505.003 - Web Shell", "https://attack.mitre.org/techniques/T1505/003/"],
        ["ET Web Client Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-web-client",
      originFolderNodeId: "suricata-etp-web-client",
      folderLabel: "Web Client",
      createdAt: "2025-11-22T08:57:31Z",
      updatedAt: "2026-04-19T16:11:09Z",
    },
    {
      id: 30018,
      source: "Emerging Threats PRO",
      category: "Web",
      groupId: "suricata-emerging",
      name: "PHP Session Fixation Pattern",
      description: "Web client request chain consistent with session fixation or token reuse.",
      severity: "medium",
      classType: "Web Application Attack",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100523,
      relatedSid: 2100523,
      totalHits: 74,
      speedValue: 21,
      lastSeenValue: 109,
      versionId: "v3",
      schedule: "6h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 4,
      quota: "per-subnet",
      protocols: "http",
      ports: "80,443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.8.0/24"],
        destinationSubnets: ["10.66.19.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "HTTP_PORTS", "HTTPS_PORTS"],
      projects: ["Hospital East Wing", "Lab Aggregate"],
      references: [
        ["MITRE T1190 - Exploit Public-Facing Application", "https://attack.mitre.org/techniques/T1190/"],
        ["ET Web Client Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-web-client",
      originFolderNodeId: "suricata-etp-web-client",
      folderLabel: "Web Client",
      createdAt: "2025-12-03T10:22:43Z",
      updatedAt: "2026-04-18T18:31:22Z",
    },
    {
      id: 30019,
      source: "Emerging Threats PRO",
      category: "Web",
      groupId: "suricata-emerging",
      name: "IIS Header Anomaly",
      description: "Suspicious HTTP header ordering against IIS-like web server traffic.",
      severity: "medium",
      classType: "Web Server Attack",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100524,
      relatedSid: 2100524,
      totalHits: 66,
      speedValue: 17,
      lastSeenValue: 85,
      versionId: "v3",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 3,
      quota: "global",
      protocols: "http",
      ports: "80,8080",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["DMZ_NET", "HOME_NET", "HTTP_PORTS"],
      projects: ["Widget Factory", "Military Base"],
      references: [
        ["MITRE T1190 - Exploit Public-Facing Application", "https://attack.mitre.org/techniques/T1190/"],
        ["ET Web Server Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-web-server",
      originFolderNodeId: "suricata-etp-web-server",
      folderLabel: "Web Server",
      createdAt: "2025-12-14T14:02:12Z",
      updatedAt: "2026-04-20T11:59:33Z",
    },
    {
      id: 30020,
      source: "Emerging Threats PRO",
      category: "Web",
      groupId: "suricata-emerging",
      name: "Rewrite Rule Abuse",
      description: "Abuse of web rewrite and proxy rules to hide a secondary payload path.",
      severity: "high",
      classType: "Web Server Attack",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100525,
      relatedSid: 2100525,
      totalHits: 52,
      speedValue: 20,
      lastSeenValue: 96,
      versionId: "v3",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 3,
      quota: "per-sensor",
      protocols: "http",
      ports: "80,443,8080",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["172.16.88.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["DMZ_NET", "EXTERNAL_NET", "PROXY_PORTS", "HTTP_PORTS"],
      projects: ["Hospital East Wing"],
      references: [
        ["MITRE T1190 - Exploit Public-Facing Application", "https://attack.mitre.org/techniques/T1190/"],
        ["ET Web Server Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-web-server",
      originFolderNodeId: "suricata-etp-web-server",
      folderLabel: "Web Server",
      createdAt: "2026-01-12T11:18:56Z",
      updatedAt: "2026-04-23T07:54:39Z",
    },
    {
      id: 30021,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "SQL Error Exfiltration",
      description: "SQL error leakage and follow-up query behavior indicating opportunistic exfiltration.",
      severity: "high",
      classType: "Attempted Information Leak",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100526,
      relatedSid: 2100526,
      totalHits: 44,
      speedValue: 13,
      lastSeenValue: 72,
      versionId: "v3",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 2,
      quota: "per-subnet",
      protocols: "tcp",
      ports: "1433,3306",
      subnetFilters: makeSubnetSelection({
        subnets: ["172.18.31.0/24"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "SSH_PORTS"],
      projects: ["Power Plant", "Lab Aggregate"],
      references: [
        ["MITRE T1041 - Exfiltration Over C2 Channel", "https://attack.mitre.org/techniques/T1041/"],
        ["ET SQL Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-sql",
      originFolderNodeId: "suricata-etp-network-services-sql",
      folderLabel: "SQL",
      createdAt: "2026-01-19T13:25:19Z",
      updatedAt: "2026-04-23T12:33:05Z",
    },
    {
      id: 30022,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "SMTP Relay Abuse",
      description: "SMTP relay usage associated with unusual outbound mail flow and relay abuse.",
      severity: "medium",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100527,
      relatedSid: 2100527,
      totalHits: 39,
      speedValue: 12,
      lastSeenValue: 63,
      versionId: "v3",
      schedule: "6h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 3,
      quota: "global",
      protocols: "smtp",
      ports: "25,465,587",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["198.51.100.0/24"],
        sourceSubnets: ["10.10.8.0/24"],
      }),
      variableUsage: ["DMZ_NET", "EXTERNAL_NET"],
      projects: ["Widget Factory", "Site Julio"],
      references: [
        ["MITRE T1071.003 - Mail Protocols", "https://attack.mitre.org/techniques/T1071/003/"],
        ["ET SMTP Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-smtp",
      originFolderNodeId: "suricata-etp-network-services-smtp",
      folderLabel: "SMTP",
      createdAt: "2025-11-30T16:17:03Z",
      updatedAt: "2026-04-21T11:26:42Z",
    },
    {
      id: 30023,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "FTP Credential Replay",
      description: "FTP login attempts using observed credential replay behavior.",
      severity: "medium",
      classType: "Credential Access",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100528,
      relatedSid: 2100528,
      totalHits: 26,
      speedValue: 8,
      lastSeenValue: 131,
      versionId: "v3",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 2,
      quota: "global",
      protocols: "ftp",
      ports: "21,20",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["10.66.19.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "THREAT_FEED_NET"],
      projects: ["Lab Aggregate"],
      references: [
        ["MITRE T1071.002 - File Transfer Protocols", "https://attack.mitre.org/techniques/T1071/002/"],
        ["ET FTP Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-ftp",
      originFolderNodeId: "suricata-etp-network-services-ftp",
      folderLabel: "FTP",
      createdAt: "2026-01-21T08:05:47Z",
      updatedAt: "2026-04-22T10:17:36Z",
    },
    {
      id: 30024,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "RPC Service Control Fan-out",
      description: "RPC-based service control fan-out that often accompanies lateral movement.",
      severity: "high",
      classType: "Trojan Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100529,
      relatedSid: 2100529,
      totalHits: 33,
      speedValue: 16,
      lastSeenValue: 90,
      versionId: "v3",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 3,
      quota: "per-host",
      protocols: "tcp",
      ports: "135,49152-49160",
      subnetFilters: makeSubnetSelection({
        subnets: ["172.18.31.0/24"],
        destinationSubnets: ["172.18.31.0/24"],
        sourceSubnets: ["172.18.31.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "SSH_PORTS"],
      projects: ["Hospital East Wing", "Military Base"],
      references: [
        ["MITRE T1021.003 - SMB/Windows Admin Shares", "https://attack.mitre.org/techniques/T1021/003/"],
        ["ET RPC Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-rpc",
      originFolderNodeId: "suricata-etp-network-services-rpc",
      folderLabel: "RPC",
      createdAt: "2026-01-23T09:47:01Z",
      updatedAt: "2026-04-22T18:58:11Z",
    },
    {
      id: 30025,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "SNMP Bulk Walk Enumeration",
      description: "Bulk SNMP walks against infrastructure and OT segments.",
      severity: "medium",
      classType: "Attempted Recon",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100530,
      relatedSid: 2100530,
      totalHits: 22,
      speedValue: 10,
      lastSeenValue: 146,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 2,
      quota: "per-subnet",
      protocols: "udp",
      ports: "161,162",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.20.0.0/24"],
        destinationSubnets: ["10.20.8.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "OT_CONTROL_PORTS"],
      projects: ["Power Plant", "Military Base"],
      references: [
        ["MITRE T1016 - System Network Configuration Discovery", "https://attack.mitre.org/techniques/T1016/"],
        ["ET SNMP Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-snmp",
      originFolderNodeId: "suricata-etp-network-services-snmp",
      folderLabel: "SNMP",
      createdAt: "2026-02-08T12:19:04Z",
      updatedAt: "2026-04-24T08:29:16Z",
    },
    {
      id: 30026,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "IMAP Login Spray",
      description: "Repeated IMAP auth attempts from remote user ranges.",
      severity: "medium",
      classType: "Attempted Admin",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100531,
      relatedSid: 2100531,
      totalHits: 18,
      speedValue: 11,
      lastSeenValue: 171,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 2,
      quota: "global",
      protocols: "tcp",
      ports: "143,993",
      subnetFilters: makeSubnetSelection({
        subnets: ["198.51.100.0/24"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["198.51.100.64/26"],
      }),
      variableUsage: ["REMOTE_USERS_NET", "HOME_NET", "HTTPS_PORTS"],
      projects: ["Site Julio"],
      references: [
        ["MITRE T1110 - Brute Force", "https://attack.mitre.org/techniques/T1110/"],
        ["ET IMAP Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-imap",
      originFolderNodeId: "suricata-etp-network-services-imap",
      folderLabel: "IMAP",
      createdAt: "2026-01-28T11:33:40Z",
      updatedAt: "2026-04-23T16:54:09Z",
    },
    {
      id: 30027,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "TELNET Fallback on Legacy Device",
      description: "Telnet fallback over legacy device management paths.",
      severity: "low",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100532,
      relatedSid: 2100532,
      totalHits: 14,
      speedValue: 7,
      lastSeenValue: 224,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 1,
      quota: "global",
      protocols: "tcp",
      ports: "23",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.20.0.0/24"],
        destinationSubnets: ["172.16.88.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["DMZ_NET", "EXTERNAL_NET"],
      projects: ["Military Base"],
      references: [
        ["MITRE T1021.001 - Remote Desktop Protocol", "https://attack.mitre.org/techniques/T1021/001/"],
        ["ET Telnet Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-network-services-telnet",
      originFolderNodeId: "suricata-etp-network-services-telnet",
      folderLabel: "TELNET",
      createdAt: "2026-03-01T10:04:12Z",
      updatedAt: "2026-04-25T06:48:31Z",
    },
    {
      id: 30028,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "TFTP Bootfile Retrieval",
      description: "TFTP bootfile pull from an unusual remote asset in an operational segment.",
      severity: "medium",
      classType: "Potentially Bad Traffic",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100533,
      relatedSid: 2100533,
      totalHits: 20,
      speedValue: 9,
      lastSeenValue: 109,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 2,
      quota: "per-sensor",
      protocols: "udp",
      ports: "69",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.20.8.0/24"],
        destinationSubnets: ["10.20.0.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "OT_CONTROL_PORTS"],
      projects: ["Power Plant"],
      references: [
        ["ET TFTP Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1105 - Ingress Tool Transfer", "https://attack.mitre.org/techniques/T1105/"],
      ],
      folderNodeId: "suricata-etp-network-services-tftp",
      originFolderNodeId: "suricata-etp-network-services-tftp",
      folderLabel: "TFTP",
      createdAt: "2026-02-14T09:17:54Z",
      updatedAt: "2026-04-24T09:08:22Z",
    },
    {
      id: 30029,
      source: "Emerging Threats PRO",
      category: "Policy & Visibility",
      groupId: "suricata-emerging",
      name: "Remote Admin Over VPN",
      description: "Administrative remote access traversing a VPN path outside the approved window.",
      severity: "high",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100534,
      relatedSid: 2100534,
      totalHits: 61,
      speedValue: 12,
      lastSeenValue: 54,
      versionId: "v3",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 3,
      quota: "global",
      protocols: "ssh",
      ports: "22,2222,3389",
      subnetFilters: makeSubnetSelection({
        subnets: ["198.51.100.64/26"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["203.0.113.192/26"],
      }),
      variableUsage: ["VPN_USERS_NET", "HOME_NET", "SSH_PORTS", "VPN_PORTS"],
      projects: ["Coastal Relay Mirror", "Site Julio"],
      references: [
        ["MITRE T1021.006 - VPN", "https://attack.mitre.org/techniques/T1021/006/"],
        ["ET Remote Access Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-policy-visibility-remote-access",
      originFolderNodeId: "suricata-etp-policy-visibility-remote-access",
      folderLabel: "REMOTE_ACCESS",
      createdAt: "2026-01-03T08:42:15Z",
      updatedAt: "2026-04-20T12:16:44Z",
    },
    {
      id: 30030,
      source: "Emerging Threats PRO",
      category: "Policy & Visibility",
      groupId: "suricata-emerging",
      name: "File Share Policy Violation",
      description: "File sharing traffic that bypasses the sanctioned collaboration boundary.",
      severity: "medium",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100535,
      relatedSid: 2100535,
      totalHits: 48,
      speedValue: 14,
      lastSeenValue: 87,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 2,
      quota: "global",
      protocols: "tcp",
      ports: "445,139",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.4.0/24"],
        destinationSubnets: ["172.18.31.0/24"],
        sourceSubnets: ["10.10.8.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "SSH_PORTS"],
      projects: ["Hospital East Wing", "Lab Aggregate"],
      references: [
        ["ET File Sharing Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1021.002 - SMB/Windows Admin Shares", "https://attack.mitre.org/techniques/T1021/002/"],
      ],
      folderNodeId: "suricata-etp-policy-visibility-file-sharing",
      originFolderNodeId: "suricata-etp-policy-visibility-file-sharing",
      folderLabel: "FILE_SHARING",
      createdAt: "2025-11-16T11:44:51Z",
      updatedAt: "2026-04-21T17:23:01Z",
    },
    {
      id: 30031,
      source: "Emerging Threats PRO",
      category: "Policy & Visibility",
      groupId: "suricata-emerging",
      name: "Dynamic DNS Abuse",
      description: "Dynamic DNS usage associated with shifting C2 infrastructure.",
      severity: "medium",
      classType: "Potentially Bad Traffic",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100536,
      relatedSid: 2100536,
      totalHits: 39,
      speedValue: 10,
      lastSeenValue: 95,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 2,
      quota: "per-subnet",
      protocols: "dns",
      ports: "53",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.66.19.0/24"],
        destinationSubnets: ["203.0.113.0/24"],
        sourceSubnets: ["198.51.100.128/25"],
      }),
      variableUsage: ["DMZ_NET", "THREAT_FEED_NET", "EXTERNAL_NET"],
      projects: ["Coastal Relay Mirror"],
      references: [
        ["ET Dynamic DNS Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1568.002 - Dynamic Resolution", "https://attack.mitre.org/techniques/T1568/002/"],
      ],
      folderNodeId: "suricata-etp-policy-visibility-dyn-dns",
      originFolderNodeId: "suricata-etp-policy-visibility-dyn-dns",
      folderLabel: "DYN_DNS",
      createdAt: "2026-02-06T07:26:43Z",
      updatedAt: "2026-04-22T20:14:37Z",
    },
    {
      id: 30032,
      source: "Emerging Threats PRO",
      category: "Policy & Visibility",
      groupId: "suricata-emerging",
      name: "Abused Service Login",
      description: "Abused service credentials arriving through an approved-looking path.",
      severity: "high",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100537,
      relatedSid: 2100537,
      totalHits: 27,
      speedValue: 11,
      lastSeenValue: 123,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "high",
      threshold: 2,
      quota: "global",
      protocols: "tcp",
      ports: "22,443",
      subnetFilters: makeSubnetSelection({
        subnets: ["198.51.100.0/24"],
        destinationSubnets: ["10.10.4.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["REMOTE_USERS_NET", "HOME_NET", "VPN_PORTS"],
      projects: ["Site Julio", "Military Base"],
      references: [
        ["ET Abused Service Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1078 - Valid Accounts", "https://attack.mitre.org/techniques/T1078/"],
      ],
      folderNodeId: "suricata-etp-policy-visibility-abused-service",
      originFolderNodeId: "suricata-etp-policy-visibility-abused-service",
      folderLabel: "TA_ABUSED_SERVICE",
      createdAt: "2026-01-09T14:57:08Z",
      updatedAt: "2026-04-24T14:42:19Z",
    },
    {
      id: 30033,
      source: "Emerging Threats PRO",
      category: "Policy & Visibility",
      groupId: "suricata-emerging",
      name: "User-Agent Policy Drift",
      description: "Unexpected browser user-agent strings in traffic that should be controlled.",
      severity: "low",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100538,
      relatedSid: 2100538,
      totalHits: 34,
      speedValue: 9,
      lastSeenValue: 69,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 2,
      quota: "global",
      protocols: "http",
      ports: "80,443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.4.0/24"],
        destinationSubnets: ["10.66.19.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "HTTP_PORTS", "HTTPS_PORTS"],
      projects: ["Widget Factory"],
      references: [
        ["ET User Agent Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1204.001 - User Execution", "https://attack.mitre.org/techniques/T1204/001/"],
      ],
      folderNodeId: "suricata-etp-policy-visibility-user-agents",
      originFolderNodeId: "suricata-etp-policy-visibility-user-agents",
      folderLabel: "User Agents",
      createdAt: "2026-02-21T08:12:39Z",
      updatedAt: "2026-04-25T11:15:27Z",
    },
    {
      id: 30034,
      source: "Emerging Threats PRO",
      category: "Industrial & SCADA",
      groupId: "suricata-emerging",
      name: "SCADA Special Command Burst",
      description: "Industrial control command burst against a monitored PLC segment.",
      severity: "critical",
      classType: "Attempted Information Leak",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100539,
      relatedSid: 2100539,
      totalHits: 51,
      speedValue: 8,
      lastSeenValue: 104,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "critical",
      threshold: 2,
      quota: "per-sensor",
      protocols: "modbus",
      ports: "502,20000",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.20.0.0/24"],
        destinationSubnets: ["10.20.8.0/24"],
        sourceSubnets: ["10.10.4.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "OT_CONTROL_PORTS"],
      projects: ["Power Plant", "Military Base"],
      references: [
        ["MITRE ATT&CK for ICS", "https://attack.mitre.org/matrices/ics/"],
        ["ET SCADA Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-industrial-scada-special",
      originFolderNodeId: "suricata-etp-industrial-scada-special",
      folderLabel: "SCADA_special",
      createdAt: "2026-01-16T15:34:18Z",
      updatedAt: "2026-04-22T16:27:41Z",
    },
    {
      id: 30035,
      source: "Emerging Threats PRO",
      category: "Operational",
      groupId: "suricata-emerging",
      name: "Current Events TLS Probe",
      description: "TLS probe behavior that aligns with current-events feed activity.",
      severity: "low",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100540,
      relatedSid: 2100540,
      totalHits: 15,
      speedValue: 8,
      lastSeenValue: 52,
      versionId: "v2",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 1,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["203.0.113.0/24"],
        sourceSubnets: ["10.10.8.0/24"],
      }),
      variableUsage: ["HOME_NET", "THREAT_FEED_NET", "HTTPS_PORTS"],
      projects: ["Coastal Relay Mirror"],
      references: [
        ["ET Current Events Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1071.001 - Web Protocols", "https://attack.mitre.org/techniques/T1071/001/"],
      ],
      folderNodeId: "suricata-etp-operational-current-events",
      originFolderNodeId: "suricata-etp-operational-current-events",
      folderLabel: "Current Events",
      createdAt: "2026-03-04T07:27:44Z",
      updatedAt: "2026-04-25T08:22:18Z",
    },
    {
      id: 30036,
      source: "Emerging Threats PRO",
      category: "Operational",
      groupId: "suricata-emerging",
      name: "JA3 Rare TLS Client Fingerprint",
      description: "Rare JA3 fingerprint across outbound TLS from a monitored host.",
      severity: "medium",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100541,
      relatedSid: 2100541,
      totalHits: 36,
      speedValue: 14,
      lastSeenValue: 148,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 2,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["198.51.100.0/24"],
        sourceSubnets: ["10.10.4.0/24"],
      }),
      variableUsage: ["HOME_NET", "HTTPS_PORTS", "THREAT_FEED_NET", "VPN_PORTS"],
      projects: ["Hospital East Wing", "Coastal Relay Mirror"],
      references: [
        ["JA3 Fingerprinting Reference", "https://github.com/salesforce/ja3"],
        ["ET JA3 Guidance", "https://rules.emergingthreats.net/open/"],
      ],
      folderNodeId: "suricata-etp-operational-ja3",
      originFolderNodeId: "suricata-etp-operational-ja3",
      folderLabel: "JA3",
      createdAt: "2026-01-06T09:44:18Z",
      updatedAt: "2026-04-23T08:12:25Z",
    },
    {
      id: 30037,
      source: "Emerging Threats PRO",
      category: "Operational",
      groupId: "suricata-emerging",
      name: "Misc TLS Relay",
      description: "Miscellaneous TLS relay behavior that still warrants visibility.",
      severity: "low",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100542,
      relatedSid: 2100542,
      totalHits: 9,
      speedValue: 7,
      lastSeenValue: 203,
      versionId: "v1",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 1,
      quota: "global",
      protocols: "tls",
      ports: "443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.12.7.0/24"],
        destinationSubnets: ["185.199.108.0/24"],
        sourceSubnets: ["203.0.113.0/24"],
      }),
      variableUsage: ["EXTERNAL_NET", "HTTPS_PORTS"],
      projects: ["Lab Aggregate"],
      references: [
        ["ET Misc Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1071 - Application Layer Protocol", "https://attack.mitre.org/techniques/T1071/"],
      ],
      folderNodeId: "suricata-etp-operational-misc",
      originFolderNodeId: "suricata-etp-operational-misc",
      folderLabel: "Misc",
      createdAt: "2026-03-12T11:08:31Z",
      updatedAt: "2026-04-24T09:19:12Z",
    },
    {
      id: 30038,
      source: "Emerging Threats PRO",
      category: "Operational",
      groupId: "suricata-emerging",
      name: "ActiveX Download Attempt",
      description: "ActiveX download attempt occurring in a policy-controlled browser path.",
      severity: "medium",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100543,
      relatedSid: 2100543,
      totalHits: 12,
      speedValue: 8,
      lastSeenValue: 167,
      versionId: "v1",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 1,
      quota: "global",
      protocols: "http",
      ports: "80,443",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.4.0/24"],
        destinationSubnets: ["10.66.19.0/24"],
        sourceSubnets: ["198.51.100.0/24"],
      }),
      variableUsage: ["HOME_NET", "DMZ_NET", "HTTP_PORTS", "HTTPS_PORTS"],
      projects: ["Site Julio"],
      references: [
        ["ET ActiveX Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1218 - Signed Binary Proxy Execution", "https://attack.mitre.org/techniques/T1218/"],
      ],
      folderNodeId: "suricata-etp-operational-activex",
      originFolderNodeId: "suricata-etp-operational-activex",
      folderLabel: "ActiveX",
      createdAt: "2026-02-20T08:51:42Z",
      updatedAt: "2026-04-25T10:02:57Z",
    },
    {
      id: 30039,
      source: "Emerging Threats PRO",
      category: "Operational",
      groupId: "suricata-emerging",
      name: "Adware PUP Redirect Chain",
      description: "Adware or PUP redirect chain leading to a low-reputation host.",
      severity: "low",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100544,
      relatedSid: 2100544,
      totalHits: 21,
      speedValue: 9,
      lastSeenValue: 128,
      versionId: "v1",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 1,
      quota: "global",
      protocols: "http",
      ports: "80,8080",
      subnetFilters: makeSubnetSelection({
        subnets: ["10.10.8.0/24"],
        destinationSubnets: ["198.51.100.128/25"],
        sourceSubnets: ["10.10.4.0/24"],
      }),
      variableUsage: ["HOME_NET", "THREAT_FEED_NET", "HTTP_PORTS"],
      projects: ["Widget Factory", "Lab Aggregate"],
      references: [
        ["ET Adware Guidance", "https://rules.emergingthreats.net/open/"],
        ["MITRE T1204 - User Execution", "https://attack.mitre.org/techniques/T1204/"],
      ],
      folderNodeId: "suricata-etp-operational-adware-pup",
      originFolderNodeId: "suricata-etp-operational-adware-pup",
      folderLabel: "Adware-PUP",
      createdAt: "2026-03-19T14:16:28Z",
      updatedAt: "2026-04-25T13:11:50Z",
    },
  ];

  function buildEtpExpansionRuleDefs() {
    return etpExpansionRuleDefs.map((rule) => ({
      ...rule,
      category: rule.category || "Operational",
      groupId: rule.groupId || "suricata-emerging",
      source: "Emerging Threats PRO",
      enabled: true,
      editable: false,
      action: rule.action || "Alert",
      relatedSid: rule.relatedSid || rule.sid,
      originFolderNodeId: rule.originFolderNodeId || rule.folderNodeId,
    }));
  }

  const ruleDefs = [
    {
      id: 20001,
      source: "Teleseer",
      category: "Default Alerts",
      groupId: "teleseer-default",
      name: "Brute Force Authentication",
      description: "Rapid repeated authentication attempts across SSH, RDP, and VPN endpoints.",
      severity: "high",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2024847,
      relatedSid: 2024847,
      totalHits: 418,
      speedValue: 26,
      lastSeenValue: 12,
      versionId: "v4",
      schedule: "auto",
      timeRange: "auto",
      severityOverride: "inherit",
      threshold: 8,
      quota: "per-host",
      protocols: "tcp",
      ports: "22,3389,5985",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.10.4.0/24", "10.10.8.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["172.18.31.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["198.51.100.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "REMOTE_USERS_NET", "SSH_PORTS", "VPN_PORTS"],
      projects: ["Site Julio", "Hospital East Wing"],
      references: [
        ["MITRE T1110 - Brute Force", "https://attack.mitre.org/techniques/T1110/"],
        ["CISA Password Spray Guidance", "https://www.cisa.gov/"],
      ],
      folderLabel: "Default Alerts",
      createdAt: "2025-11-08T14:22:15Z",
      updatedAt: "2026-04-23T16:10:41Z",
    },
    {
      id: 20002,
      source: "Teleseer",
      category: "Default Alerts",
      groupId: "teleseer-default",
      name: "Credential Dumping Indicator",
      description: "Correlates suspicious LSASS access, memory reads, and lateral movement artifacts.",
      severity: "critical",
      classType: "Trojan Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2024861,
      relatedSid: 2024861,
      totalHits: 83,
      speedValue: 38,
      lastSeenValue: 67,
      versionId: "v4",
      schedule: "auto",
      timeRange: "auto",
      severityOverride: "critical",
      threshold: 4,
      quota: "global",
      protocols: "tcp",
      ports: "445,5985",
      subnetFilters: {
        subnets: { mode: "include", checked: ["172.18.31.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["10.10.4.0/24"], manual: [] },
        sourceSubnets: { mode: "exclude", checked: ["203.0.113.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "DMZ_NET", "VPN_USERS_NET", "SSH_PORTS"],
      projects: ["Hospital East Wing", "Lab Aggregate"],
      references: [
        ["MITRE T1003 - OS Credential Dumping", "https://attack.mitre.org/techniques/T1003/"],
        ["Microsoft Credential Theft Guidance", "https://learn.microsoft.com/security/"],
      ],
      folderLabel: "Default Alerts",
      createdAt: "2025-12-19T09:11:02Z",
      updatedAt: "2026-04-22T11:18:09Z",
    },
    {
      id: 20003,
      source: "Teleseer",
      category: "Default Alerts",
      groupId: "teleseer-default",
      name: "Port Scan Wide Sweep",
      description: "Broad scan behavior traversing internal VLANs and exposed services.",
      severity: "medium",
      classType: "Attempted Recon",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2024870,
      relatedSid: 2024870,
      totalHits: 9700,
      speedValue: 19,
      lastSeenValue: 24,
      versionId: "v4",
      schedule: "1h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 20,
      quota: "per-subnet",
      protocols: "tcp",
      ports: "1:1024,3389,445",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.10.4.0/24", "10.10.8.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["172.18.31.0/24", "192.168.44.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["203.0.113.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "EXTERNAL_NET", "HTTP_PORTS", "HTTPS_PORTS"],
      projects: ["Site Julio", "Power Plant"],
      references: [
        ["MITRE T1046 - Network Service Discovery", "https://attack.mitre.org/techniques/T1046/"],
        ["CISA Reconnaissance Guidance", "https://www.cisa.gov/"],
      ],
      folderLabel: "Default Alerts",
      createdAt: "2025-11-14T10:31:17Z",
      updatedAt: "2026-04-21T18:02:56Z",
    },
    {
      id: 20004,
      source: "Teleseer",
      category: "Default Alerts",
      groupId: "teleseer-default",
      name: "Outbound Data Spike",
      description: "Unusual egress volume over a short interval from a monitored workspace.",
      severity: "high",
      classType: "Policy Violation",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2024891,
      relatedSid: 2024891,
      totalHits: 3200,
      speedValue: 44,
      lastSeenValue: 9,
      versionId: "v4",
      schedule: "6h",
      timeRange: "7d",
      severityOverride: "high",
      threshold: 3,
      quota: "per-sensor",
      protocols: "tcp",
      ports: "443,8443,3128",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.66.19.0/24", "172.16.88.0/24"], manual: [] },
        destinationSubnets: { mode: "exclude", checked: ["198.51.100.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["10.10.4.0/24", "10.10.8.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "DMZ_NET", "PROXY_PORTS", "THREAT_FEED_NET"],
      projects: ["Widget Factory", "Lab Aggregate"],
      references: [
        ["MITRE T1041 - Exfiltration Over C2 Channel", "https://attack.mitre.org/techniques/T1041/"],
        ["NIST Data Exfiltration Guidance", "https://www.nist.gov/"],
      ],
      folderLabel: "Default Alerts",
      createdAt: "2025-12-04T15:05:44Z",
      updatedAt: "2026-04-24T08:41:02Z",
    },
    {
      id: 30001,
      source: "Emerging Threats PRO",
      category: "Policy Visibility",
      groupId: "suricata-emerging",
      name: "SMB Lateral Movement Burst",
      description: "Flags sudden east-west SMB fan-out with credential reuse artifacts.",
      severity: "critical",
      classType: "Trojan Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100459,
      relatedSid: 2100459,
      totalHits: 1216,
      speedValue: 16,
      lastSeenValue: 17,
      versionId: "v3",
      schedule: "1h",
      timeRange: "24h",
      severityOverride: "critical",
      threshold: 8,
      quota: "global",
      protocols: "tcp",
      ports: "139,445",
      subnetFilters: {
        subnets: { mode: "include", checked: ["172.18.31.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["172.18.31.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["172.18.31.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "DMZ_NET"],
      projects: ["Hospital East Wing", "Military Base"],
      references: [
        ["MITRE T1021 - Remote Services", "https://attack.mitre.org/techniques/T1021/"],
        ["MITRE T1078 - Valid Accounts", "https://attack.mitre.org/techniques/T1078/"],
      ],
      folderNodeId: "suricata-etp-network-services-netbios",
      originFolderNodeId: "suricata-etp-network-services-netbios",
      folderLabel: "NETBIOS",
      createdAt: "2025-12-26T06:20:11Z",
      updatedAt: "2026-04-23T12:29:10Z",
    },
    {
      id: 30002,
      source: "Emerging Threats PRO",
      category: "Network Services",
      groupId: "suricata-emerging",
      name: "Outbound DNS Tunneling Pattern",
      description: "Finds high-entropy DNS labels and anomalous TXT answer ratios.",
      severity: "medium",
      classType: "Bad Known",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100467,
      relatedSid: 2100467,
      totalHits: 294,
      speedValue: 24,
      lastSeenValue: 44,
      versionId: "v3",
      schedule: "6h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 12,
      quota: "per-subnet",
      protocols: "dns",
      ports: "53",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.66.19.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["203.0.113.0/24", "198.51.100.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["10.10.4.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "EXTERNAL_NET", "THREAT_FEED_NET"],
      projects: ["Site Julio", "Coastal Relay Mirror"],
      references: [
        ["MITRE T1071.004 - DNS", "https://attack.mitre.org/techniques/T1071/004/"],
        ["CISA DNS Security Guidance", "https://www.cisa.gov/"],
      ],
      folderNodeId: "suricata-etp-network-services-dns",
      originFolderNodeId: "suricata-etp-network-services-dns",
      folderLabel: "DNS",
      createdAt: "2025-12-30T11:41:09Z",
      updatedAt: "2026-04-22T07:14:49Z",
    },
    {
      id: 30003,
      source: "Emerging Threats PRO",
      category: "Operational",
      groupId: "suricata-emerging",
      name: "TLS Beaconing to Rare ASN",
      description: "Detects fixed-interval TLS beaconing to uncommon autonomous systems.",
      severity: "low",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100494,
      relatedSid: 2100494,
      totalHits: 41,
      speedValue: 12,
      lastSeenValue: 149,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "low",
      threshold: 2,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.12.7.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["203.0.113.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["10.10.4.0/24"], manual: [] },
      },
      variableUsage: ["EXTERNAL_NET", "HTTPS_PORTS", "THREAT_FEED_NET", "VPN_PORTS"],
      projects: ["Coastal Relay Mirror", "Site Julio"],
      references: [
        ["MITRE T1071.001 - Web Protocols", "https://attack.mitre.org/techniques/T1071/001/"],
        ["Rare ASN Beaconing Notes", "https://www.cisa.gov/"],
      ],
      folderNodeId: "suricata-etp-operational-ja3",
      originFolderNodeId: "suricata-etp-operational-ja3",
      folderLabel: "JA3",
      createdAt: "2026-01-08T09:14:03Z",
      updatedAt: "2026-04-24T10:28:31Z",
    },
    {
      id: 30004,
      source: "Emerging Threats PRO",
      category: "Industrial & SCADA",
      groupId: "suricata-emerging",
      name: "Modbus Control Register Change",
      description: "Flags control writes to PLC register ranges outside the maintenance window.",
      severity: "high",
      classType: "Attempted Information Leak",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 2100502,
      relatedSid: 2100502,
      totalHits: 61,
      speedValue: 9,
      lastSeenValue: 66,
      versionId: "v2",
      schedule: "12h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 2,
      quota: "per-sensor",
      protocols: "modbus",
      ports: "502,20000",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.20.0.0/24", "10.20.8.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["172.24.7.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["10.10.4.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "DMZ_NET", "OT_CONTROL_PORTS"],
      projects: ["Power Plant", "Military Base"],
      references: [
        ["MITRE T1047 - Windows Management Instrumentation", "https://attack.mitre.org/techniques/T1047/"],
        ["OT Control Change Guidance", "https://www.cisa.gov/"],
      ],
      folderNodeId: "suricata-etp-industrial-scada-scada",
      originFolderNodeId: "suricata-etp-industrial-scada-scada",
      folderLabel: "SCADA",
      createdAt: "2026-01-15T13:34:20Z",
      updatedAt: "2026-04-22T15:46:09Z",
    },
    ...buildEtpExpansionRuleDefs(),
    {
      id: 40001,
      source: "Custom Detection",
      category: "App Performance",
      groupId: "custom-rules",
      name: "Slow API Abuse on Customer Checkout Path",
      description: "Performance-oriented rule for abusive API patterns affecting checkout transactions.",
      severity: "low",
      classType: "Misc Activity",
      enabled: false,
      editable: true,
      action: "Pass",
      sid: 3301006,
      relatedSid: 2024877,
      totalHits: 52,
      speedValue: 43,
      lastSeenValue: 1440,
      versionId: "v4",
      schedule: "24h",
      timeRange: "7d",
      severityOverride: "low",
      threshold: 1,
      quota: "per-host",
      protocols: "http",
      ports: "80,8080,8443",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.10.4.0/24", "10.10.8.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["10.66.19.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["10.10.4.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "DMZ_NET", "PROXY_PORTS", "HTTP_PORTS"],
      projects: ["teleseer-dummy", "Widget Factory"],
      references: [
        ["Checkout latency tuning note", "https://docs.internal.local/checkout"],
        ["MITRE T1499 - Endpoint Denial of Service", "https://attack.mitre.org/techniques/T1499/"],
      ],
      folderNodeId: "suricata-custom-app-performance",
      originFolderNodeId: "suricata-custom-app-performance",
      folderLabel: "App Performance",
      createdAt: "2025-12-19T06:22:58Z",
      updatedAt: "2026-04-21T09:12:15Z",
      ruleStateTags: [{ label: "Broken", tone: "danger" }],
      statusDot: "gray",
    },
    {
      id: 40002,
      source: "Custom Detection",
      category: "Network Hygiene",
      groupId: "custom-rules",
      name: "Remote Admin Fallback on Bastion",
      description: "Visibility rule for unexpected remote-admin fallback chains on bastion hosts.",
      severity: "high",
      classType: "Policy Violation",
      enabled: true,
      editable: true,
      action: "Alert",
      sid: 3301007,
      relatedSid: 2025001,
      totalHits: 19,
      speedValue: 16,
      lastSeenValue: 240,
      versionId: "v4",
      schedule: "6h",
      timeRange: "24h",
      severityOverride: "high",
      threshold: 2,
      quota: "per-sensor",
      protocols: "ssh",
      ports: "22,2222,3389",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.10.4.0/24", "10.10.8.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["172.18.31.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["198.51.100.0/24", "203.0.113.0/25"], manual: [] },
      },
      variableUsage: ["HOME_NET", "REMOTE_USERS_NET", "VPN_PORTS", "SSH_PORTS"],
      projects: ["teleseer-dummy", "Site Julio"],
      references: [
        ["MITRE T1021.001 - Remote Desktop Protocol", "https://attack.mitre.org/techniques/T1021/001/"],
        ["Bastion hardening checklist", "https://docs.internal.local/bastion"],
      ],
      folderNodeId: "suricata-custom-network-hygiene",
      originFolderNodeId: "suricata-custom-network-hygiene",
      folderLabel: "Network Hygiene",
      createdAt: "2026-02-03T10:17:29Z",
      updatedAt: "2026-04-24T18:06:53Z",
    },
    {
      id: 40003,
      source: "Custom Detection",
      category: "Operational Visibility",
      groupId: "custom-rules",
      name: "Suspicious VPN Failover Probe",
      description: "Correlates uncommon VPN fallback behavior with repeated authentication attempts.",
      severity: "medium",
      classType: "Misc Activity",
      enabled: true,
      editable: true,
      action: "Alert",
      sid: 3301008,
      relatedSid: 2025002,
      totalHits: 11,
      speedValue: 22,
      lastSeenValue: 180,
      versionId: "v4",
      schedule: "12h",
      timeRange: "7d",
      severityOverride: "medium",
      threshold: 1,
      quota: "global",
      protocols: "tls",
      ports: "1194,51820,443",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.12.7.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["198.51.100.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["198.51.100.64/26", "203.0.113.192/26"], manual: [] },
      },
      variableUsage: ["HOME_NET", "VPN_PORTS", "SSH_PORTS", "VPN_USERS_NET"],
      projects: ["Coastal Relay Mirror", "teleseer-dummy"],
      references: [
        ["MITRE T1021.006 - VPN", "https://attack.mitre.org/techniques/T1021/006/"],
        ["VPN failover runbook", "https://docs.internal.local/vpn"],
      ],
      folderNodeId: "suricata-custom-operational-visibility",
      originFolderNodeId: "suricata-custom-operational-visibility",
      folderLabel: "Operational Visibility",
      createdAt: "2026-03-11T12:20:30Z",
      updatedAt: "2026-04-25T08:20:14Z",
    },
    {
      id: 50001,
      source: "Imported 2025-03-01",
      category: "Imported 2025-03-01",
      groupId: "imported-rules",
      name: "Rare JA3 Handshake from Vendor Jump Host",
      description: "Visibility rule for uncommon TLS fingerprints on approved operational jump hosts.",
      severity: "medium",
      classType: "Misc Activity",
      enabled: true,
      editable: false,
      action: "Alert",
      sid: 3301010,
      relatedSid: 2025001,
      totalHits: 154,
      speedValue: 31,
      lastSeenValue: 240,
      versionId: "v3",
      schedule: "24h",
      timeRange: "24h",
      severityOverride: "medium",
      threshold: 2,
      quota: "global",
      protocols: "tls",
      ports: "443,8443",
      subnetFilters: {
        subnets: { mode: "include", checked: ["10.12.7.0/24"], manual: [] },
        destinationSubnets: { mode: "include", checked: ["203.0.113.0/24"], manual: [] },
        sourceSubnets: { mode: "include", checked: ["10.10.4.0/24"], manual: [] },
      },
      variableUsage: ["HOME_NET", "HTTPS_PORTS", "THREAT_FEED_NET"],
      projects: ["Hospital East Wing", "Coastal Relay Mirror"],
      references: [
        ["Vendor change advisory", "https://docs.internal.local/vendor"],
        ["MITRE T1071.001 - Web Protocols", "https://attack.mitre.org/techniques/T1071/001/"],
      ],
      folderNodeId: "suricata-imported-root",
      originFolderNodeId: "suricata-etp-operational-ja3",
      folderLabel: "Imported 2025-03-01",
      createdAt: "2026-01-07T09:44:08Z",
      updatedAt: "2026-04-25T09:33:41Z",
    },
  ];

  const incidentDefs = [
    {
      id: "grp-bruteforce-auth",
      ruleId: 20001,
      hosts: [
        "core-auth-01.hula.local",
        "edge-vpn-02.hula.local",
        "10.10.4.19",
        "172.20.9.44",
      ],
      events: [
        {
          timestampOffsetMinutes: 5,
          host: "core-auth-01.hula.local",
          source: "185.17.91.45",
          destination: "10.10.4.19:22",
          protocol: "SSH",
          sensor: "sensor-west-03",
          status: "queued",
        },
        {
          timestampOffsetMinutes: 8,
          host: "edge-vpn-02.hula.local",
          source: "45.159.221.88",
          destination: "172.20.9.44:443",
          protocol: "TLS",
          sensor: "sensor-west-03",
          status: "ingested",
        },
        {
          timestampOffsetMinutes: 11,
          host: "10.10.4.19",
          source: "185.17.91.45",
          destination: "10.10.4.19:3389",
          protocol: "RDP",
          sensor: "sensor-west-03",
          status: "partial",
        },
      ],
    },
    {
      id: "grp-smb-lateral",
      ruleId: 30001,
      hosts: [
        "ws-finance-22.hula.local",
        "dc-core-01.hula.local",
        "ws-legal-04.hula.local",
        "172.18.31.77",
        "172.18.31.110",
        "172.18.31.205",
      ],
      events: [
        {
          timestampOffsetMinutes: 17,
          host: "ws-finance-22.hula.local",
          source: "172.18.31.77",
          destination: "172.18.31.205:445",
          protocol: "SMB",
          sensor: "sensor-dc-01",
          status: "ingested",
        },
        {
          timestampOffsetMinutes: 18,
          host: "dc-core-01.hula.local",
          source: "172.18.31.110",
          destination: "172.18.31.77:445",
          protocol: "SMB",
          sensor: "sensor-dc-01",
          status: "ingested",
        },
        {
          timestampOffsetMinutes: 21,
          host: "ws-legal-04.hula.local",
          source: "172.18.31.205",
          destination: "172.18.31.110:445",
          protocol: "SMB",
          sensor: "sensor-dc-01",
          status: "dropped",
        },
      ],
    },
    {
      id: "grp-dns-tunnel",
      ruleId: 30002,
      hosts: ["dmz-proxy-06.hula.local", "host-analytics-12.hula.local"],
      events: [
        {
          timestampOffsetMinutes: 44,
          host: "dmz-proxy-06.hula.local",
          source: "10.66.19.4",
          destination: "8.8.8.8:53",
          protocol: "DNS",
          sensor: "sensor-dmz-02",
          status: "ingested",
        },
        {
          timestampOffsetMinutes: 56,
          host: "host-analytics-12.hula.local",
          source: "10.66.19.85",
          destination: "1.1.1.1:53",
          protocol: "DNS",
          sensor: "sensor-dmz-02",
          status: "partial",
        },
      ],
    },
    {
      id: "grp-cred-dump",
      ruleId: 20002,
      hosts: ["win-admin-09.hula.local", "dc-core-01.hula.local", "172.18.31.77"],
      events: [
        {
          timestampOffsetMinutes: 67,
          host: "win-admin-09.hula.local",
          source: "172.18.31.77",
          destination: "172.18.31.9:445",
          protocol: "SMB",
          sensor: "sensor-dc-01",
          status: "ingested",
        },
        {
          timestampOffsetMinutes: 123,
          host: "dc-core-01.hula.local",
          source: "172.18.31.9",
          destination: "172.18.31.1:5985",
          protocol: "WinRM",
          sensor: "sensor-dc-01",
          status: "queued",
        },
      ],
    },
    {
      id: "grp-tls-beacon",
      ruleId: 30003,
      hosts: ["edge-egress-02.hula.local"],
      events: [
        {
          timestampOffsetMinutes: 149,
          host: "edge-egress-02.hula.local",
          source: "10.12.7.5",
          destination: "205.185.118.22:443",
          protocol: "TLS",
          sensor: "sensor-edge-01",
          status: "stale",
        },
      ],
    },
  ];

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function toGroupId(source) {
    if (source === "Teleseer") return "teleseer-default";
    if (source === "Emerging Threats PRO") return "suricata-emerging";
    if (source === "Custom Detection") return "custom-rules";
    if (source === "Imported 2025-03-01") return "imported-rules";
    return "custom-rules";
  }

  function formatRelativeRuleAge(minutes) {
    if (!Number.isFinite(minutes) || minutes < 0) return "-";
    if (minutes === 0) return "Just now";
    if (minutes < 60) return `${minutes}m ago`;
    if (minutes < 1440) return `${Math.round(minutes / 60)}h ago`;
    if (minutes < 10080) return `${Math.round(minutes / 1440)}d ago`;
    return `${Math.round(minutes / 10080)}w ago`;
  }

  function getPortLiteralCardinality(token) {
    const clean = String(token || "").trim().replace(/^!/, "");
    if (!clean) return 0;
    const rangeMatch = clean.match(/^(\d{1,5})-(\d{1,5})$/);
    if (rangeMatch) {
      const start = Number(rangeMatch[1]);
      const end = Number(rangeMatch[2]);
      if (!Number.isFinite(start) || !Number.isFinite(end) || end < start) return 0;
      return (end - start) + 1;
    }
    return /^\d{1,5}$/.test(clean) ? 1 : 0;
  }

  function getVariableCount(variable) {
    const type = String(variable?.type || "").trim().toLowerCase();
    const values = Array.isArray(variable?.literalValues) ? variable.literalValues : [];
    if (type.startsWith("port")) {
      return values.reduce((sum, token) => sum + getPortLiteralCardinality(token), 0);
    }
    return values.length;
  }

  function formatVariableCountLabel(type, count) {
    const safeCount = Math.max(0, Number(count) || 0);
    const isSubnet = String(type || "").toLowerCase().startsWith("subnet") || String(type || "").toLowerCase().startsWith("address");
    const singular = isSubnet ? "Address" : "Port";
    const plural = safeCount === 1 ? singular : (singular === "Address" ? "Addresses" : "Ports");
    return `${safeCount} ${plural}`;
  }

  function buildTooltipLines(items) {
    return (Array.isArray(items) ? items : [])
      .map((item) => String(item ?? "").trim())
      .filter(Boolean)
      .join(" · ");
  }

  function normalizeList(values) {
    return [...new Set((Array.isArray(values) ? values : []).map((item) => String(item ?? "").trim()).filter(Boolean))];
  }

  function deriveVariables(graph, ruleRows) {
    const reverseIndex = new Map();
    graph.variables.forEach((variable) => {
      const source = String(variable.name || "").trim();
      normalizeList(variable.referenceItems).forEach((target) => {
        if (!reverseIndex.has(target)) reverseIndex.set(target, new Set());
        reverseIndex.get(target).add(source);
      });
    });

    const directRuleIndex = new Map();
    (Array.isArray(ruleRows) ? ruleRows : []).forEach((rule) => {
      normalizeList(rule.variableUsage).forEach((variableName) => {
        if (!directRuleIndex.has(variableName)) directRuleIndex.set(variableName, new Set());
        directRuleIndex.get(variableName).add(rule.id);
      });
    });

    function collectDependencyNames(name, seen = new Set()) {
      if (seen.has(name)) return seen;
      seen.add(name);
      const children = reverseIndex.get(name);
      if (children) {
        children.forEach((child) => collectDependencyNames(child, seen));
      }
      return seen;
    }

    return graph.variables.map((variable) => {
      const name = String(variable.name || "").trim();
      const directReferencedBy = reverseIndex.has(name)
        ? [...reverseIndex.get(name)].sort((left, right) => left.localeCompare(right, undefined, { sensitivity: "base" }))
        : [];
      const dependencyNames = collectDependencyNames(name, new Set());
      const usedByRules = [];
      const usedByProjects = [];
      (Array.isArray(ruleRows) ? ruleRows : []).forEach((rule) => {
        const usesVariable = normalizeList(rule.variableUsage).some((usage) => dependencyNames.has(usage));
        if (!usesVariable) return;
        if (!usedByRules.includes(rule.name)) usedByRules.push(rule.name);
        normalizeList(rule.projects).forEach((project) => {
          if (!usedByProjects.includes(project)) usedByProjects.push(project);
        });
      });

      const literalValues = normalizeList(variable.literalValues);
      const referenceItems = normalizeList(variable.referenceItems);
      const valueCount = getVariableCount(variable);
      return {
        name,
        type: variable.type || "Port",
        valueCount,
        valueItems: literalValues,
        literalValues: literalValues,
        valueEntries: [
          ...referenceItems.map((ref) => ({ kind: "variable", value: ref, exclude: false })),
          ...literalValues.map((value) => {
            const exclude = String(value).startsWith("!");
            return {
              kind: "literal",
              value: exclude ? String(value).slice(1).trim() : value,
              exclude,
            };
          }),
        ],
        valueLabel: formatVariableCountLabel(variable.type, valueCount),
        valueTooltip: buildTooltipLines([...referenceItems, ...literalValues]),
        referencedBy: directReferencedBy.length,
        references: directReferencedBy.length,
        referencedByItems: directReferencedBy,
        referenceItems,
        usedByRules: usedByRules.length,
        usedByAlerts: usedByRules.length,
        usedByRuleItems: usedByRules,
        projects: usedByProjects.length,
        projectItems: usedByProjects,
        createdAt: variable.createdAt,
        updatedAt: variable.updatedAt,
        description: String(variable.description || "").trim(),
        valueOptions: variable.valueOptions || [],
      };
    });
  }

  function buildRuleRuntimeRow(rule, variableRows) {
    const enabled = rule.enabled !== false;
    const projects = normalizeList(rule.projects);
    const groupId = toGroupId(rule.source);
    const references = normalizeList(rule.references).length
      ? normalizeList(rule.references)
      : [`reference: ${groupId}`, `reference: sid:${rule.sid}`];
    const variableUsage = normalizeList(rule.variableUsage);
    const subnetFilters = clone(rule.subnetFilters || {
      subnets: { mode: "include", checked: [], manual: [] },
      destinationSubnets: { mode: "include", checked: [], manual: [] },
      sourceSubnets: { mode: "include", checked: [], manual: [] },
    });
    const speedValue = Number(rule.speedValue) || 1;
    const lastSeenValue = Number(rule.lastSeenValue) || 0;
    const row = {
      id: rule.id,
      source: rule.source,
      category: rule.category || "Default Alerts",
      groupId,
      name: rule.name,
      description: rule.description,
      action: rule.action || "Alert",
      sid: rule.sid,
      relatedSid: rule.relatedSid || rule.sid,
      classType: rule.classType || "Misc Activity",
      severity: rule.severity || "low",
      speed: `${speedValue}µs`,
      speedValue,
      lastSeen: formatRelativeRuleAge(lastSeenValue),
      lastSeenValue,
      totalHits: Number(rule.totalHits) || 0,
      enabled,
      editable: Boolean(rule.editable),
      ruleStateTags: Array.isArray(rule.ruleStateTags) ? clone(rule.ruleStateTags) : [],
      statusDot: rule.statusDot || (enabled ? "green" : "gray"),
      folderNodeId: rule.folderNodeId || "",
      originFolderNodeId: rule.originFolderNodeId || rule.folderNodeId || "",
      folderLabel: rule.folderLabel || "",
      createdAt: rule.createdAt,
      updatedAt: rule.updatedAt,
      versionId: rule.versionId || "v4",
      schedule: rule.schedule || "auto",
      timeRange: rule.timeRange || "auto",
      severityOverride: rule.severityOverride || "inherit",
      threshold: Number(rule.threshold) || 1,
      quota: rule.quota || "global",
      protocols: rule.protocols || "any",
      ports: rule.ports || "",
      subnetFilters,
      projects,
      projectItems: projects,
      projectCount: projects.length,
      variableUsage,
      references,
      referenceGroupId: groupId,
      referenceSid: String(rule.referenceSid || rule.sid),
    };
    if (Array.isArray(variableRows) && variableRows.length) {
      row.variableUsageItems = variableRows
        .filter((variable) => variableUsage.includes(variable.name))
        .map((variable) => variable.name);
    } else {
      row.variableUsageItems = variableUsage.slice();
    }
    if (enabled && !Array.isArray(row.ruleStateTags)) {
      row.ruleStateTags = [];
    }
    if (!enabled && !row.ruleStateTags.length) {
      row.ruleStateTags = [{ label: "Broken", tone: "danger" }];
    }
    return row;
  }

  function deriveManageAlertsRules(graph, variableRows) {
    const runtimeRules = graph.rules.map((rule) => buildRuleRuntimeRow(rule, variableRows));
    const teleseerRules = runtimeRules.filter((rule) => rule.source === "Teleseer");
    const suricataRules = runtimeRules.filter((rule) => rule.source !== "Teleseer");
    const ruleById = runtimeRules.reduce((index, rule) => {
      index[String(rule.id)] = rule;
      return index;
    }, {});
    return {
      rules: runtimeRules,
      suricataRules,
      teleseerRules,
      ruleById,
      catalogCounts: clone(graph.catalogCounts || {}),
    };
  }

  function deriveViewerAlertsData(manageRules) {
    const sidebarGroups = [
      {
        id: "teleseer-default",
        source: "Teleseer",
        name: "Default Alerts",
        description: "Baseline curated detections",
      },
      {
        id: "suricata-emerging",
        source: "Emerging Threats PRO",
        name: "Emerging Threats Pro",
        description: "Community and premium signatures",
      },
      {
        id: "custom-rules",
        source: "Custom Detection",
        name: "My Custom Detections",
        description: "Workspace-specific detections and tests",
      },
      {
        id: "imported-rules",
        source: "Imported 2025-03-01",
        name: "Imported 2025-03-01",
        description: "Imported signatures staged for review",
      },
    ].map((group) => {
      const rules = manageRules.rules.filter((rule) => rule.groupId === group.id);
      return {
        ...group,
        count: rules.reduce((sum, rule) => sum + (Number(rule.totalHits) || 0), 0),
      };
    });

    const sidebarRules = manageRules.rules.map((rule) => ({
      id: rule.id,
      groupId: rule.groupId,
      name: rule.name,
      description: rule.description,
      severity: rule.severity,
      enabled: rule.enabled,
      projects: rule.projectItems.length,
      totalHits: rule.totalHits,
      sid: rule.sid,
      classtype: rule.classType,
      versionId: rule.versionId,
      schedule: rule.schedule,
      timeRange: rule.timeRange,
      severityOverride: rule.severityOverride,
      threshold: rule.threshold,
      quota: rule.quota,
      protocols: rule.protocols,
      ports: rule.ports,
      subnetFilters: clone(rule.subnetFilters),
      references: clone(rule.references),
      referenceSid: rule.referenceSid,
      referenceGroupId: rule.referenceGroupId,
    }));

    const alertGroups = incidentDefs.map((incident) => {
      const rule = manageRules.ruleById[String(incident.ruleId)];
      const events = incident.events.map((event) => ({
        timestamp: Date.now() - (Number(event.timestampOffsetMinutes) || 0) * 60 * 1000,
        host: event.host,
        source: event.source,
        destination: event.destination,
        protocol: event.protocol,
        sensor: event.sensor,
        status: event.status,
      }));
      const oldestAt = Math.min(...events.map((event) => event.timestamp));
      const lastSeenAt = Math.max(...events.map((event) => event.timestamp));
      return {
        id: incident.id,
        ruleId: incident.ruleId,
        severity: rule?.severity || "low",
        name: rule?.name || incident.id,
        description: rule?.description || "",
        provider: rule?.source || "Unknown",
        ruleFamily: rule?.category || rule?.source || "",
        hosts: clone(incident.hosts),
        lastSeenAt,
        oldestAt,
        count: rule?.totalHits || events.length,
        events,
      };
    });

    return {
      ruleGroups: sidebarGroups,
      rules: sidebarRules,
      alertGroups,
    };
  }

  function buildAlertingData() {
    const variableGraph = {
      variables: clone(variableDefs),
      rules: clone(ruleDefs),
      incidents: clone(incidentDefs),
      catalogCounts: clone(etpCatalogCounts),
    };
    const variables = deriveVariables(variableGraph, ruleDefs);
    const manageAlerts = deriveManageAlertsRules(variableGraph, variables);
    const viewerAlerts = deriveViewerAlertsData(manageAlerts);
    return {
      projectPool: clone(projectPool),
      graph: variableGraph,
      variables,
      manageAlerts,
      viewerAlerts,
      catalogCounts: clone(etpCatalogCounts),
    };
  }

  const alertingData = buildAlertingData();
  global.TeleseerAlertingData = {
    projectPool: clone(projectPool),
    graph: clone(alertingData.graph),
    deriveVariables,
    deriveManageAlertsRules,
    deriveViewerAlertsData,
    buildAlertingData,
  };
  global.TeleseerAppData = global.TeleseerAppData || {};
  if (!global.TeleseerAppData.alerting) {
    global.TeleseerAppData.alerting = clone(alertingData);
  }
})(window);
