(function initTeleseerAppData(global) {
  const favoriteProjects = [
    {
      id: "power-plant",
      label: "Power Plant",
      icon: "../icons/icon_place.svg",
      count: "",
    },
    {
      id: "widget-factory",
      label: "Widget Factory",
      icon: "../icons/icon_place.svg",
      count: "",
    },
    {
      id: "military-base",
      label: "Military Base",
      icon: "../icons/icon_place.svg",
      count: "",
    },
  ];

  const workspaceProjectCatalog = [
    {
      id: "teleseer-dummy",
      name: "teleseer-dummy",
      subtext: "Hub workspace · 10.24.18.0/24",
      icon: "../icons/icon_project_fill.svg",
      viewerLink: "../viewer/viewer.html",
      files: "25",
      hosts: "25",
      subnets: "6",
      vlans: "5",
      size: "9.1 GB",
      duration: "15d 12h 12m",
      created: "Just now",
      status: {
        tone: "uploading",
        label: "Uploading 30%",
        extra: "sensor snr-phx-07",
      },
      tags: [
        { label: "Agent", tone: "agent" },
        { label: "OT-Lab", tone: "ot" },
        { label: "Hub", tone: "hub" },
      ],
    },
    {
      id: "site-julio",
      name: "Site Julio",
      subtext: "remote-west-grid · 172.16.40.0/21",
      icon: "../icons/icon_project_fill.svg",
      files: "25",
      hosts: "21",
      subnets: "4",
      vlans: "6",
      size: "3.3 GB",
      duration: "3d 5h 6m",
      created: "30m ago",
      status: {
        tone: "queued",
        label: "Queued",
        extra: "awaiting parser slot",
      },
      tags: [
        { label: "Agent", tone: "agent" },
        { label: "Remote", tone: "remote" },
        { label: "Hub", tone: "hub" },
      ],
    },
    {
      id: "hospital-east-wing",
      name: "Hospital East Wing",
      subtext: "remote-med-east · 192.168.44.0/24",
      icon: "../icons/icon_project_fill.svg",
      files: "25",
      hosts: "37",
      subnets: "8",
      vlans: "3",
      size: "9.5 GB",
      duration: "15d 12h 12m",
      created: "2h ago",
      status: {
        tone: "warning",
        label: "Sync delayed 14m",
        extra: "sensor heartbeat stale",
      },
      tags: [
        { label: "Agent", tone: "agent" },
        { label: "OT-Lab", tone: "ot" },
        { label: "Hub", tone: "hub" },
      ],
    },
    {
      id: "coastal-relay-mirror",
      readOnly: true,
      name: "Coastal Relay Mirror",
      subtext: "remote-maritime · 10.201.70.0/24",
      icon: "../icons/icon_project_fill.svg",
      files: "12",
      hosts: "14",
      subnets: "2",
      vlans: "2",
      size: "2.7 GB",
      duration: "6h 42m",
      created: "Yesterday",
      status: {
        tone: "restricted",
        label: "Read-only mirror",
        extra: "partner workspace",
      },
      tags: [
        { label: "Remote", tone: "remote" },
        { label: "Read-only", tone: "read-only" },
        { label: "Hub", tone: "hub" },
      ],
    },
    {
      id: "power-plant",
      name: "Power Plant",
      subtext: "ot-generation · 10.54.10.0/24",
      icon: "../icons/icon_project_fill.svg",
      files: "18",
      hosts: "44",
      subnets: "7",
      vlans: "9",
      size: "6.4 GB",
      duration: "8d 2h 18m",
      created: "4h ago",
      status: {
        tone: "ready",
        label: "Indexed",
        extra: "sensor snr-plant-02",
      },
      tags: [
        { label: "Agent", tone: "agent" },
        { label: "OT-Lab", tone: "ot" },
      ],
    },
    {
      id: "widget-factory",
      name: "Widget Factory",
      subtext: "manufacturing-east · 172.16.88.0/24",
      icon: "../icons/icon_project_fill.svg",
      files: "31",
      hosts: "62",
      subnets: "9",
      vlans: "11",
      size: "12.8 GB",
      duration: "12d 7h 03m",
      created: "6h ago",
      status: {
        tone: "syncing",
        label: "Syncing 72%",
        extra: "remote workspace handoff",
      },
      tags: [
        { label: "Remote", tone: "remote" },
        { label: "OT-Lab", tone: "ot" },
      ],
    },
    {
      id: "military-base",
      name: "Military Base",
      subtext: "restricted-garrison · 10.77.20.0/22",
      icon: "../icons/icon_project_fill.svg",
      files: "14",
      hosts: "29",
      subnets: "5",
      vlans: "4",
      size: "4.9 GB",
      duration: "2d 19h 44m",
      created: "Yesterday",
      status: {
        tone: "restricted",
        label: "Restricted",
        extra: "RBAC controlled",
      },
      tags: [
        { label: "Agent", tone: "agent" },
        { label: "Read-only", tone: "read-only" },
      ],
    },
    {
      id: "lab-aggregate",
      name: "Lab Aggregate",
      subtext: "research-lab · 192.168.64.0/21",
      icon: "../icons/icon_project_fill.svg",
      files: "22",
      hosts: "36",
      subnets: "6",
      vlans: "8",
      size: "7.6 GB",
      duration: "5d 11h 28m",
      created: "2d ago",
      status: {
        tone: "warning",
        label: "Parser delayed",
        extra: "malformed pcap batch",
      },
      tags: [
        { label: "Agent", tone: "agent" },
        { label: "Hub", tone: "hub" },
      ],
    },
  ];

  const launcherProjectRows = workspaceProjectCatalog.map((project) => ({
    selected: false,
    ...project,
  }));

  const alertingVariables = [
    {
      name: "HTTP_PORTS",
      type: "Port",
      valueCount: 4,
      valueItems: ["80", "81", "8080", "8888"],
      usedByRules: 18,
      usedByRuleItems: [
        "TLS_INSPECTION_EDGE",
        "WEB_SHELL_EXFIL",
        "JSP_DROP_STAGE",
        "L7_PROXY_BYPASS",
        "EXPLOIT_KIT_FETCH",
      ],
      referencedBy: 4,
      referencedByItems: [
        "HOME_NET",
        "DMZ_NET",
        "WEB_PORTS",
        "PROXY_PORTS",
      ],
      projects: 2,
      projectItems: ["Site Julio", "Hospital East Wing"],
      createdAt: "2026-01-14T08:12:19Z",
      updatedAt: "2026-04-19T13:32:44Z",
      usedByAlerts: 18,
      references: 4,
      referenceItems: [
        "HOME_NET",
        "DMZ_NET",
        "WEB_PORTS",
        "PROXY_PORTS",
      ],
      valueLabel: "4 Ports",
      valueOptions: [
        "1 Port",
        "2 Ports",
        "4 Ports",
        "8 Ports",
        "12 Ports",
        "Any",
      ],
    },
    {
      name: "HTTPS_PORTS",
      type: "Port",
      valueCount: 12,
      valueItems: [
        "443",
        "444",
        "5443",
        "6443",
        "7443",
        "8443",
        "9443",
        "10443",
        "11443",
        "12443",
        "13443",
        "14443",
      ],
      usedByRules: 312,
      usedByRuleItems: [
        "TLS_INSPECTION_EDGE",
        "OUTBOUND_PROXY",
        "SINGLE_SIGN_ON",
        "CLOUD_API_GATEWAY",
        "EDR_UPDATE_PIPELINE",
        "PARTNER_PORTAL",
        "WEB_ADMIN_CONSOLE",
      ],
      referencedBy: 0,
      referencedByItems: [],
      projects: 5,
      projectItems: [
        "Site Julio",
        "Hospital East Wing",
        "Widget Factory",
        "Power Plant",
        "Coastal Relay Mirror",
      ],
      createdAt: "2025-11-22T12:05:44Z",
      updatedAt: "2026-04-20T17:41:07Z",
      usedByAlerts: 312,
      references: 0,
      valueLabel: "12 Ports",
      valueOptions: ["4 Ports", "8 Ports", "12 Ports", "24 Ports", "Any"],
    },
    {
      name: "SSH_PORTS",
      type: "Port",
      valueCount: 435,
      valueItems: ["22", "2222", "22022-22454"],
      valueTooltip: "22 · 2222 · 22022-22454",
      usedByRules: 96,
      usedByRuleItems: [
        "BRUTE_FORCE_MONITOR",
        "MGMT_BASTION_ALLOW",
        "OT_JUMP_HOST",
        "VPN_FALLBACK_ACCESS",
      ],
      referencedBy: 1,
      referencedByItems: ["PROXY_PORTS"],
      projects: 3,
      projectItems: ["Power Plant", "Military Base", "Lab Aggregate"],
      createdAt: "2025-09-03T19:44:11Z",
      updatedAt: "2026-04-12T10:02:33Z",
      usedByAlerts: 96,
      references: 1,
      referenceItems: ["PROXY_PORTS"],
      valueLabel: "435 Ports",
      valueOptions: ["22", "22,2222", "435 Ports", "Any"],
    },
    {
      name: "VPN_PORTS",
      type: "Port",
      valueCount: 2,
      valueItems: ["1194", "51820"],
      usedByRules: 12,
      usedByRuleItems: [
        "REMOTE_ACCESS_ALLOW",
        "VPN_FAILOVER",
        "FIELD_SERVICE_TUNNEL",
      ],
      referencedBy: 2,
      referencedByItems: ["HOME_NET", "REMOTE_USERS_NET"],
      projects: 1,
      projectItems: ["Coastal Relay Mirror"],
      createdAt: "2026-02-05T14:27:09Z",
      updatedAt: "2026-04-16T09:18:21Z",
      usedByAlerts: 12,
      references: 2,
      referenceItems: ["HOME_NET", "REMOTE_USERS_NET"],
      valueLabel: "2 Ports",
      valueOptions: ["1 Port", "2 Ports", "4 Ports", "8 Ports"],
    },
    {
      name: "HOME_NET",
      type: "Subnet",
      valueCount: 4,
      valueItems: [
        "10.24.18.0/24",
        "172.16.40.0/21",
        "192.168.44.0/24",
        "10.201.70.0/24",
      ],
      usedByRules: 287,
      usedByRuleItems: [
        "HOME_NET_ALLOW",
        "INTERNAL_DNS",
        "WORKSTATION_EGRESS",
        "PATCH_MGMT",
        "OT_DMZ_BOUNCE",
        "BACKUP_REPLICATION",
      ],
      referencedBy: 4,
      referencedByItems: [
        "HTTP_PORTS",
        "HTTPS_PORTS",
        "DMZ_NET",
        "REMOTE_USERS_NET",
      ],
      projects: 6,
      projectItems: [
        "Site Julio",
        "Hospital East Wing",
        "Widget Factory",
        "Military Base",
        "Power Plant",
        "Lab Aggregate",
      ],
      createdAt: "2025-10-18T07:53:30Z",
      updatedAt: "2026-04-18T21:16:54Z",
      usedByAlerts: 287,
      references: 4,
      referenceItems: [
        "HTTP_PORTS",
        "HTTPS_PORTS",
        "DMZ_NET",
        "REMOTE_USERS_NET",
      ],
      valueLabel: "4 Addresses",
      valueOptions: ["2 Addresses", "4 Addresses", "8 Addresses", "Any"],
    },
    {
      name: "DMZ_NET",
      type: "Subnet",
      valueCount: 3,
      valueItems: [
        "10.54.10.0/24",
        "172.16.88.0/24",
        "192.0.2.64/27",
      ],
      usedByRules: 45,
      usedByRuleItems: [
        "DMZ_TO_WAN",
        "PUBLISH_EDGE",
        "PORTAL_REVERSE_PROXY",
        "SMTP_RELAY",
      ],
      referencedBy: 2,
      referencedByItems: ["HOME_NET", "WEB_PORTS"],
      projects: 3,
      projectItems: ["Hospital East Wing", "Widget Factory", "Lab Aggregate"],
      createdAt: "2025-12-02T15:09:51Z",
      updatedAt: "2026-04-17T16:08:12Z",
      usedByAlerts: 45,
      references: 2,
      referenceItems: ["HOME_NET", "WEB_PORTS"],
      valueLabel: "3 Addresses",
      valueOptions: ["1 Address", "3 Addresses", "4 Addresses", "Any"],
    },
    {
      name: "REMOTE_USERS_NET",
      type: "Subnet",
      valueCount: 2,
      valueItems: ["198.51.100.0/24", "203.0.113.0/25"],
      usedByRules: 22,
      usedByRuleItems: [
        "REMOTE_ACCESS_ALLOW",
        "FIELD_SERVICE_TUNNEL",
        "MFA_ENFORCEMENT",
      ],
      referencedBy: 1,
      referencedByItems: ["HOME_NET"],
      projects: 2,
      projectItems: ["Site Julio", "Coastal Relay Mirror"],
      createdAt: "2026-01-29T11:03:26Z",
      updatedAt: "2026-04-15T08:36:08Z",
      usedByAlerts: 22,
      references: 1,
      referenceItems: ["HOME_NET"],
      valueLabel: "2 Addresses",
      valueOptions: ["1 Address", "2 Addresses", "4 Addresses", "Any"],
    },
    {
      name: "THREAT_FEED_NET",
      type: "Subnet",
      valueCount: 5,
      valueItems: [
        "185.199.108.0/22",
        "91.218.230.0/24",
        "203.0.113.128/25",
        "198.51.100.128/25",
        "192.0.2.160/27",
      ],
      usedByRules: 8,
      usedByRuleItems: [
        "IOC_QUARANTINE",
        "C2_BLOCKLIST",
        "EXFIL_EDGE_DENY",
      ],
      referencedBy: 0,
      referencedByItems: [],
      projects: 1,
      projectItems: ["Lab Aggregate"],
      createdAt: "2026-03-07T06:22:40Z",
      updatedAt: "2026-04-21T19:58:11Z",
      usedByAlerts: 8,
      references: 0,
      valueLabel: "5 Addresses",
      valueOptions: ["2 Addresses", "4 Addresses", "5 Addresses", "8 Addresses"],
    },
  ];

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  const existingAppData = global.TeleseerAppData || {};
  global.TeleseerAppData = {
    ...existingAppData,
    projects: {
      favorites: clone(favoriteProjects),
      launcherRows: clone(launcherProjectRows),
      catalog: clone(workspaceProjectCatalog),
    },
    alerting: existingAppData.alerting || {
      ruleProjectPool: workspaceProjectCatalog.map((project) => project.name),
      variables: clone(alertingVariables),
    },
  };
})(window);
